### ISSUE TITLE
Version of marian used for training

### ISSUE THREAD

**Issue by XapaJIaMnu** [mozilla/firefox-translations-training#30]
We should be training with `marian-nmt/marian-dev` HEAD (current head is safe), not with `browsermt/marian-dev`. `browsermt/marian-dev` should only be used for binarizing the intgemm models that run into the browser.

**Comment by eu9ene** [comment]
Is it possible to just merge upstream marian-dev to browsermt fork to avoid using two Marians?

**Comment by XapaJIaMnu** [comment]
Upstream marian  is developed largely behind close doors and occasionally massive pull requests happen which makes maintaining a "light" patchset on top of it very difficult. I kept merging until last christmas more or less but then it just became too much work.

For now, two marian forks would be the easiest, sorry ;/

**Comment by andrenatal** [comment]
@XapaJIaMnu what you mean behind closed doors? If there's a slight interest of distributing this here, this statement would need to be clarified and explained internally. 

I understand this might not be the case with the other browser vendors your group are possibly working, but since Mozilla is legally binded by contract along the consortium of universities, we are supposed to know officially who are the real owners of marian-dev that would keep maintaining it in the case the organization decides to continue utilizing it as part of our suite of products after the end of the grant program. cc @kpu

**Comment by XapaJIaMnu** [comment]
https://github.com/marian-nmt/marian-dev/blob/master/LICENSE.md

Marian is MIT, it's lead developers are employed by Microsoft. The direction that the lead developers take is discussed internally at their workplace and eventually patches trickle down to the public master. 

Because of that merging our big patches into upstream marian is quite cumbersome, as they do not necessarily share the vision of the upstream developers. In particular, the WASM codepath, as well some of the optimisations we have done for fast decoding would not be accepted upstream, hence why I recommend that we use upstream marian for training (since it has more features and is faster) and our fork for the binary models and decoding.

We keep trying to push our changes upstream but the process will be slow and uncertain.

**Comment by andrenatal** [comment]
Thanks for the clarification.
