### ISSUE TITLE
`merge-mono` fails when no data is available

### ISSUE THREAD

**Issue by AmitMY** [mozilla/firefox-translations-training#339]
In the config, it says:
```yaml
  # to be translated by the backward model to augment teacher corpus with back-translations
  # leave empty to skip augmentation step (high resource languages)
  mono-trg: [ ]
```

I would like to leave it empty for now.
However, that causes the following command:
```bash
bash pipeline/clean/merge-mono.sh "/data/data/spoken-signed/spoken_to_signed_bpe6/clean/mono.signed.gz" 20000000  >> /data/logs/spoken-signed/spoken_to_signed_bpe6/merge_mono_signed.log 2>&1
```

Which results in 
```bash
+ set -euo pipefail
+ test -v BIN
+ echo '###### Merging monolingual datasets'
###### Merging monolingual datasets
+ output=/data/data/spoken-signed/spoken_to_signed_bpe6/clean/mono.signed.gz
+ max_sentences=20000000
+ datasets=("${@:3}")
+ COMPRESSION_CMD=pigz
+ echo '### Merging the following datasets:'
### Merging the following datasets:
pipeline/clean/merge-mono.sh: line 36: datasets: unbound variable
```
(unbound, because there is no 3rd argument)

This config should work, at the very least for experimentation. 
If it is deemed unsupported, the error should be better

**Comment by eu9ene** [comment]
I believe we settled on always using back-translations since they are useful for both high and low resource languages so I simplified the pipeline and removed extra conditions. If they are not needed for your use case, feel free to add them back in Snakemake file and create a PR. Overall, the simpler the pipeline the more chances that it will be properly maintained.
