### ISSUE TITLE
Backward steps are duplicated

### ISSUE THREAD

**Issue by eu9ene** [mozilla/firefox-translations-training#474]
<img width="526" alt="Screenshot 2024-03-08 at 9 20 39 AM" src="https://github.com/mozilla/firefox-translations-training/assets/2486505/ec078564-6d3d-45f7-962d-87a3dd461542">

**Comment by La0** [comment]
@eu9ene We could skip the group re-publication if it already exists when publishing with recursive lookups enabled.

This duplication happens because parts of the same graph are shared amongst some of the runs from your list (which makes sense).

As we run several times the code against different task groups, the only way to avoid duplication is to check if the group already exists on W&B (could be a pre-flight step in the code, to list all available groups)

**Comment by eu9ene** [comment]
I see, ok, then we should check before uploading.

**Comment by eu9ene** [comment]
More duplication examples:

<img width="472" alt="Screenshot 2024-03-18 at 2 29 31 PM" src="https://github.com/mozilla/firefox-translations-training/assets/2486505/f0f7d42d-58cf-4141-bc6f-c821c1596751">
