### ISSUE TITLE
Issues with uploaded experiments

### ISSUE THREAD

**Issue by eu9ene** [mozilla/firefox-translations-training#518]
Some weird things I noticed in https://wandb.ai/moz-translations/lt-en:

- teacher-ensemble evals is empty
- group logs doesn't have any metrics
- group logs is missing for some groups
- quantized is missing
This group is listed in the docs https://firefox-ci-tc.services.mozilla.com/tasks/groups/KYZvXC6jTPG7A4j80SrYlQ and have a lot of evals that we don't see in W&B

**Comment by La0** [comment]
@vrigal will work on it this week

**Comment by vrigal** [comment]
* teacher-ensemble/teacher/quantize are empty
  * 60 similar errors, because scores are not displayed in the logs anymore but rather are printed to `.metrics` and `.metrics.json` files :
  ```                                                                                                                                                                               
  [task 2024-03-30T22:13:09.778Z] Computing the BLEU score.                                                                                                                         
  [task 2024-03-30T22:13:09.778Z] Computing the chrF score.                                                                                                                         
  [task 2024-03-30T22:13:09.778Z] Writing /home/ubuntu/tasks/task_171183664836330/artifacts/aug-noise_devtest.metrics.json                                                          
  [task 2024-03-30T22:13:09.778Z] Writing the metrics in the older "text" format: /home/ubuntu/tasks/task_171183664836330/artifacts/aug-noise_devtest.metrics                       
  ``` 
  * The issue here is that Taskcluster publication for evaluation runs is based on the folder hierarchy legacy code, which is entirely based on log files (having these folder structure make possible publishing everything as group_lors artifacts though, helping with troobleshot/data preservation).                                                   
  * I'll update this so it uses `.metrics` files directly and publish a dedicated MR. 

* group logs doesn't have any metrics
  * This is due to the issue mentioned above.
* group logs missing on some groups                                                                                                      
  * I was not able to reproduce, but I suppose that is a bug. I'll have to look at it a bit more.                                        
* KYZvXC6jTPG7A4j80SrYlQ have a lot of evals that we don't see in W&B
  * This is also due to the issue mentioned above (I see 60 tasks, 30 for teacher, 15 for teacher ensemble, 15 for quantized, others have been published on training runs).

**Comment by vrigal** [comment]
I opened #565 which address the main problem here (missing eval data).

I noticed by the way that metrics from the actual runs (here `student` and `finetuned-student`) are missing from the table in `group_logs`, but this should be a minor issue I think, we could open a follow-up for it.
I found no hint about the missing `group_logs`.
