### ISSUE TITLE
Checkpointing training

### ISSUE THREAD

**Issue by kpu** [mozilla/firefox-translations-training#54]
A good high-resource model can't be trained in 24 (or even 36) hours on one node of CSD3.  We need to checkpoint and allow longer training.  Pulling issue out of #52.  Normally we submit `#SBATCH --array=1-7%1` to allow the job to have up to 7 runs interrupted by training. Not sure how to fit this (or an equivalent) into snakemake.  Maybe a kludge is producing numbered files as "output" to make a sequence of steps, though producing this file should happen late in the job.

**Comment by eu9ene** [comment]
As a workaround, you can increase the number of restarts in `https://github.com/mozilla/firefox-translations-training/blob/main/profiles/slurm/config.yaml`, `restart-times` option. You can max out the time limit that the cluster allows you to set and every time the job is killed with timeout, snakemake will restart it and delete only the desired output `model.npz.best-chrf.npz`, which is not great but it will be recreated on the next validation (might be of worse quality though).

We can think of a more elegant way to support this, but we don't know the number of required jobs in advance, so we might end up with a bunch of empty jobs scheduled.

**Comment by kpu** [comment]
Yeah I agree a bunch of empty jobs would be annoying. One kludge I've done with that is just make the job alter itself when it's done.

**Comment by eu9ene** [comment]
I checked how job arrays works and it's good that it's possible to check status of all jobs using the same job id. We have full control over how a slurm job is scheduled and how job status is checked, so we can add a special property/parameter to training rules, then propagate it to `sbatch` and change `slurm/status.py` to distinguish between array jobs and regular ones.

**Comment by kpu** [comment]
I wish to make clear that this issue is preventing us from using HPC.  All runs are currently using one machine at a time despite the potential parallelism in some steps.  This is causing the French and Polish models to take substantially longer.

**Comment by eu9ene** [comment]
I'm looking at it. Job arrays work, but it will require some changes in the pipeline to make Snakemake work. Specifically, we'll need copying of the final model result in the very end of the training, otherwise, Snakemake gets confused by already presented result file. I'm still figuring out how Snakemake metadata might interfere with the process when the job got killed. Also, I'm experimenting with cancelling the rest of the job array when the job is completed. Overall it looks doable but requires some testing time.

**Comment by eu9ene** [comment]
I tested job arrays with cancellation and they don't work. The only place where we can do cancellation is status.py script and the issue is we can't catch the moment when one step of the array has already finished and another one hasn't started yet. When another step starts snakemake deletes the output file. 

I propose another workaround - using retries + output file copying, I'm testing it and it works. The downside is that if there is a bug a job will be launched N times before we can even inspect logs properly.
