### ISSUE TITLE
Duplicate runs in W&B

### ISSUE THREAD

**Issue by eu9ene** [mozilla/firefox-translations-training#729]
https://wandb.ai/moz-translations/tr-en/workspace?nw=nwuserepavlov

https://firefox-ci-tc.services.mozilla.com/tasks/groups/SDD81N6sRu61LOL4xZJc-Q

<img width="758" alt="Screenshot 2024-07-09 at 11 54 51 AM" src="https://github.com/mozilla/firefox-translations-training/assets/2486505/eda5dd12-4de5-433f-95b2-80fbfee5f151">

**Comment by eu9ene** [comment]
Same here https://wandb.ai/moz-translations/vi-en/workspace?nw=nwuserepavlov

I guess it started recently

**Comment by vrigal** [comment]
This is a serious bug, as all the following evaluation tasks fail with this message:
```
Multiple W&B runs already exist with name 'teacher-1': [<Run moz-translations/tr-en/ged9nebc (finished)>, <Run moz-translations/tr-en/shovl7mn (finished)>, …]. No data will be published.
```
This may be caused by the current implementation, that list existing runs before publishing (as the ID is required to resume a run in W&B). A race condition is possible among 2+ tasks (those tasks ran in ~3minutes), creating multiple runs with a similar display name, then causing this bug.

This somehow confirms our approach using unique run IDs (& name) is certainly the way to go.
